### ISSUE TITLE
Design Issue with station to station as the transport for signatory vs noise.

### ISSUE THREAD

**Issue by zmanian** [tendermint/signatory#3]
So the identity key for a node and consensus signing key are typically the same key. The consensus signing key will need to live inside signatory. When a node is bootstrapping, it can't attest it's identity because the key lives in signatory.

We could detach the node identity from the consensus signing key or we could use just use noise and have a longterm X25519 key that is used to boostrap the secure channel.

**Comment by tarcieri** [comment]
A few options here:

1) Use Noise :wink:
2) Since this is all going to be greenfield anyway, the STS protocol implementation can be built on Signatory, and actually use an HSM-backed key (or whatever is configured) for STS too. We'd definitely want to make sure things are nicely domain separated if we do that
3) Use a separate key for identity and signing. The KMS nodes could have explicit identity certs. The KMS could separately prove possession of the signing keys it claims to possess in its keyring if that's desirable

**Comment by tarcieri** [comment]
This should probably be filed either in `tendermint/kms` or a different Tendermint/Cosmos repo.
